apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: u30-eks
  region: us-east-1

vpc:
  id: "vpc-0ad02b8f6add1de30"
  subnets:
    Public:
      us-east-1a:
        id: "subnet-025977455fd1bc1bb"
      us-east-1b:
        id: "subnet-0b220f74a50fe4d98"

managedNodeGroups:
  - name: vt1-ng-1d
    instanceType: vt1.3xlarge
    volumeSize: 200
    instancePrefix: vt1-ng-1d-worker
    ami: ami-09124d6a37695ffd8
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyName: lyhsiang
    subnets:
    - subnet-025977455fd1bc1bb
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh u30-eks
