apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vt1-demo-eks-cluster
  region: ap-northeast-1

vpc:
  id: "vpc-0aff96bfa5e83803c"
  subnets:
    Public:
      ap-northeast-1a:
        id: "subnet-010ab8c7961262929"

managedNodeGroups:
  - name: vt1-ng-1a
    instanceType: vt1.3xlarge
    volumeSize: 200
    instancePrefix: vt1-ng-1a-worker
    ami: ami-07535e1e770e5ce34
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyName: vt1-key-NRT
    subnets:
    - ap-northeast-1a
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh vt1-demo-eks-cluster
