apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: u30-eks
  region: ap-northeast-1

vpc:
  id: "vpc-06e8174333e6234d7"
  subnets:
    Public:
      ap-northeast-1a:
        id: "subnet-0e017847884b340e7"

managedNodeGroups:
  - name: vt1-ng-1a
    instanceType: vt1.3xlarge
    volumeSize: 200
    instancePrefix: vt1-ng-1a-worker
    ami: ami-07535e1e770e5ce34
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
    ssh:
      allow: true
      publicKeyName: vt1-key-NRT
    subnets:
    - ap-northeast-1a
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh u30-eks
